export const carouselImages = [
  {
    id: 1,
    src: "/pages/home/about/slider-image-1.jpg",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 2,
    src: "/pages/home/about/slider-image-2.jpg",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 3,
    src: "/pages/home/about/slider-image-3.jpg",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 4,
    src: "/pages/home/about/slider-image-4.jpg",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 5,
    src: "/pages/home/about/slider-image-5.jpg",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 6,
    src: "/pages/home/about/slider-image-6.jpg",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 7,
    src: "/pages/home/about/slider-image-7.jpg",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
];
