export const carouselImages = [
  {
    id: 1,
    src: "/pages/home/about/slider-image-1.webp",
    isPriority: false,
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 2,
    src: "/pages/home/about/slider-image-2.webp",
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 3,
    src: "/pages/home/about/slider-image-3.webp",
    isPriority: false,
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 4,
    src: "/pages/home/about/slider-image-4.webp",
    isPriority: false,
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 5,
    src: "/pages/home/about/slider-image-5.webp",
    isPriority: false,
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 6,
    src: "/pages/home/about/slider-image-6.webp",
    isPriority: false,
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
  {
    id: 7,
    src: "/pages/home/about/slider-image-7.webp",
    isPriority: false,
    alt: "Image of Mario Lima",
    width: 590,
    height: 1080,
  },
];
